version: '3.4'

services:
  microserusuarios:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  microsercursos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"


  microsercalificaciones:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10000:80"


  ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

